# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p6bP_5Th-XMWUTt8TekhorQCu8zQS3K7
"""

!pip install -q groq duckduckgo-search streamlit

from groq import Groq

client = Groq(api_key="")

from duckduckgo_search import DDGS

def search(query):
    with DDGS() as ddgs:
        results = ddgs.text(query, max_results=3)
        return results

chat_history = []

def agent(query):
    # save memory
    chat_history.append(query)

    # decide if we need search
    context = ""

    if "search" in query.lower():
        context = search(query)

    # build prompt
    prompt = f"""
You are a smart assistant.

Chat history:
{chat_history}

Context:
{context}

Question:
{query}
"""

    # call Groq
    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[{"role": "user", "content": prompt}]
    )

    return response.choices[0].message.content

print(agent("what is RAG"))

print(agent("search explain machine learning"))